export default {
  // TODOS
  SET_TODOS: "SET_TODOS",
  REORDER_TODOS: "REORDER_TODOS",

  // LOADING
  SET_LOADING_STATUS: "SET_LOADING_STATUS",

  // THEME
  SET_COLOR_THEME: "SET_COLOR_THEME",

  // EDITING
  SET_EDITING_TODO: "SET_EDITING_TODO",
};
